# Change these first
owner: mt190502
repo: uptime.mtaha.dev

status-website:
  cname: uptime.mtaha.dev
  logoUrl: https://avatars.githubusercontent.com/u/62564400
  name: uptime.mtaha.dev
  introTitle: "**uptime.mtaha.dev** is uptime monitor for my infrastructure"
  introMessage: k8s.tf's Uptime Monitor
  navbar:
    - title: Infra
      href: https://github.com/$OWNER/k8s.tf
    - title: Source
      href: https://github.com/$OWNER/$REPO

sites:
  - name: Anki Sync Server
    url: https://anki.mtaha.dev/sync/beta
    expectedStatusCodes: [405]
  - name: Atlantis
    url: https://atlantis.mtaha.dev/events
    expectedStatusCodes: [200, 401, 403, 405]
  - name: Grafana
    url: https://dash.mtaha.dev
    expectedStatusCodes: [200]
  - name: Miniflux
    url: https://rss.mtaha.dev
    expectedStatusCodes: [200]
  - name: Nightscout
    url: https://t1d.mtaha.dev
    expectedStatusCodes: [200]
  - name: Radicale
    url: https://dav.mtaha.dev
    expectedStatusCodes: [200]
  - name: Redmine
    url: https://red.mtaha.dev
    expectedStatusCodes: [200, 401, 403]
  - name: Umami
    url: https://umami.mtaha.dev
    expectedStatusCodes: [200]
